<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="3" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="65748" started-at="2015-10-30T16:36:58Z" finished-at="2015-10-30T16:38:04Z">
    <groups>
    </groups>
    <test name="SecondTest" duration-ms="58379" started-at="2015-10-30T16:36:58Z" finished-at="2015-10-30T16:37:56Z">
      <class name="LearningTestNG.TestNGAnotation_1">
        <test-method status="PASS" signature="beforeClass(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc]" name="beforeClass" is-config="true" duration-ms="13221" started-at="2015-10-30T13:36:58Z" finished-at="2015-10-30T13:37:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[46.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[WINDOWS]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2015-10-30T13:37:11Z" finished-at="2015-10-30T13:37:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login()[pri:1, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc]" name="login" duration-ms="38631" started-at="2015-10-30T13:37:11Z" finished-at="2015-10-30T13:37:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at LearningTestNG.TestNGAnotation_1.login(TestNGAnotation_1.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc]" name="afterMethod" is-config="true" duration-ms="462" started-at="2015-10-30T13:37:50Z" finished-at="2015-10-30T13:37:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TestNGAnotation_1.login()[pri:1, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc]" name="logout" duration-ms="0" started-at="2015-10-30T13:37:50Z" depends-on-methods="LearningTestNG.TestNGAnotation_1.login" finished-at="2015-10-30T13:37:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGAnotation_1.logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGAnotation_1.logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:LearningTestNG.TestNGAnotation_1@3b81a1bc]" name="afterClass" is-config="true" duration-ms="6049" started-at="2015-10-30T13:37:50Z" finished-at="2015-10-30T13:37:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- LearningTestNG.TestNGAnotation_1 -->
    </test> <!-- SecondTest -->
    <test name="ThirdTest" duration-ms="65239" started-at="2015-10-30T16:36:58Z" finished-at="2015-10-30T16:38:03Z">
      <class name="LearningTestNG.TestNGAnotation_1">
        <test-method status="PASS" signature="beforeClass(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:LearningTestNG.TestNGAnotation_1@180bc464]" name="beforeClass" is-config="true" duration-ms="10025" started-at="2015-10-30T13:36:58Z" finished-at="2015-10-30T13:37:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[41.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[MAC]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:LearningTestNG.TestNGAnotation_1@180bc464]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2015-10-30T13:37:08Z" finished-at="2015-10-30T13:37:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login()[pri:1, instance:LearningTestNG.TestNGAnotation_1@180bc464]" name="login" duration-ms="37353" started-at="2015-10-30T13:37:08Z" finished-at="2015-10-30T13:37:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at LearningTestNG.TestNGAnotation_1.login(TestNGAnotation_1.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LearningTestNG.TestNGAnotation_1@180bc464]" name="afterMethod" is-config="true" duration-ms="587" started-at="2015-10-30T13:37:45Z" finished-at="2015-10-30T13:37:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TestNGAnotation_1.login()[pri:1, instance:LearningTestNG.TestNGAnotation_1@180bc464] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@180bc464]" name="logout" duration-ms="0" started-at="2015-10-30T13:37:46Z" depends-on-methods="LearningTestNG.TestNGAnotation_1.login" finished-at="2015-10-30T13:37:46Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGAnotation_1.logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@180bc464] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGAnotation_1.logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@180bc464] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:LearningTestNG.TestNGAnotation_1@180bc464]" name="afterClass" is-config="true" duration-ms="17247" started-at="2015-10-30T13:37:46Z" finished-at="2015-10-30T13:38:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- LearningTestNG.TestNGAnotation_1 -->
    </test> <!-- ThirdTest -->
    <test name="FirstTest" duration-ms="65748" started-at="2015-10-30T16:36:58Z" finished-at="2015-10-30T16:38:04Z">
      <class name="LearningTestNG.TestNGAnotation_1">
        <test-method status="PASS" signature="beforeClass(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:LearningTestNG.TestNGAnotation_1@6108b2d7]" name="beforeClass" is-config="true" duration-ms="15475" started-at="2015-10-30T13:36:58Z" finished-at="2015-10-30T13:37:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[IE]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[WINDOWS]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:LearningTestNG.TestNGAnotation_1@6108b2d7]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2015-10-30T13:37:13Z" finished-at="2015-10-30T13:37:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login()[pri:1, instance:LearningTestNG.TestNGAnotation_1@6108b2d7]" name="login" duration-ms="43954" started-at="2015-10-30T13:37:13Z" finished-at="2015-10-30T13:37:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at LearningTestNG.TestNGAnotation_1.login(TestNGAnotation_1.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LearningTestNG.TestNGAnotation_1@6108b2d7]" name="afterMethod" is-config="true" duration-ms="622" started-at="2015-10-30T13:37:57Z" finished-at="2015-10-30T13:37:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TestNGAnotation_1.login()[pri:1, instance:LearningTestNG.TestNGAnotation_1@6108b2d7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@6108b2d7]" name="logout" duration-ms="0" started-at="2015-10-30T13:37:58Z" depends-on-methods="LearningTestNG.TestNGAnotation_1.login" finished-at="2015-10-30T13:37:58Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGAnotation_1.logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@6108b2d7] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGAnotation_1.logout()[pri:0, instance:LearningTestNG.TestNGAnotation_1@6108b2d7] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:LearningTestNG.TestNGAnotation_1@6108b2d7]" name="afterClass" is-config="true" duration-ms="5680" started-at="2015-10-30T13:37:58Z" finished-at="2015-10-30T13:38:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- LearningTestNG.TestNGAnotation_1 -->
    </test> <!-- FirstTest -->
  </suite> <!-- Suite -->
</testng-results>
